### ISSUE TITLE
Error during WebSocket handshake: 'Connection' header value is not 'Upgrade'

### ISSUE THREAD

**Issue by tcoulter** [faye/faye#228]
I'm using Faye via the NodeAdapter over HTTPS. When Mobile Safari tries to connect to the Faye server, it'll show an alert saying the page cannot be loaded, and then it will show this message in the console log:

`Error during WebSocket handshake: 'Connection' header value is not 'Upgrade'`

I saw a similar issue when using a rails version of the faye-websocket gem, and I've also seen issues on the net where this occurs while using nginx; but I'm not using any server in between Faye, so this appears to be an issue with Faye itself (or my configuration). I've upgraded iOS on the device to the latest version (6.1.3), as well as upgraded Faye to its latest version (0.8.9). EDIT: See comment below. It's not isolated to iOS.

My configuration is the same shown on this page, using port 443. I have no non-bayeux endpoints added:

http://faye.jcoglan.com/node.html

Any ideas? Your help is much appreciated.

Tim

**Comment by 350050183** [comment]
It looks like wss(web socket ) protocol not compitable with https.

**Comment by jcoglan** [comment]
@350050183 I'm not sure what you mean or how it relates to this issue. Could you give a more detailed explanation?

**Comment by 350050183** [comment]
It does not relate to this project,I just google the problem "Connection' header value is not 'Upgrade' ",it is about the nodejs,when i disable ssl connected to my chat server,the issue is gone.

**Comment by jcoglan** [comment]
We have had issues with missing `Connection` headers before, but that was due to a bug in a pre-release version of Passenger. We've also had issues with SSL compatibility before but that was a bug in the Node `https` module not handing off incoming decrypted data to the `data` listener.

If you can provide a small example program that demonstrates the problem happening I can investigate further. You should probably open a new issue as well so we're not notifying the other people in this thread on every message.

**Comment by saeidalidadi** [comment]
I have this problem too, but its ok on other system and the same browser.
My server is node and the module which I used is `socket.io`

**Comment by jcoglan** [comment]
@saeidalidadi Socket.IO is a separate product that has nothing do to with Faye. Are you sure you've posed this to the right project?

**Comment by zhonglanwen** [comment]
Socket.IO is a separate product that has nothing do to with Faye.
