### ISSUE TITLE
ReferenceError: Faye is not defined

### ISSUE THREAD

**Issue by chetang** [faye/faye#352]
I have been using faye in my Emberjs application and seems to work fine as expected. But my test suite crashes with faye is not defined. 
[Link to Stack question]( http://stackoverflow.com/questions/27243632/testing-emberjs-app-fails-due-to-referenceerror-faye-is-not-defined)

**Comment by molefrog** [comment]
As it [was answered](http://stackoverflow.com/a/27830540/1654564) on StackOverflow the reason app doesn't work is because QUnit defines global variable `module`, so that following lines are executed:
```javascript
if (typeof module !== 'undefined') 
  module.exports = Faye;
 ```
However we can fix this behaviour by using more strict assertion:
```javascript
if(typeof module === "object" && typeof module.exports === "object")
```

@jcoglan will it be appropriate to make pull request?

**Comment by jcoglan** [comment]
@molefrog I feel like any solution to this is inherently going to get into an arms race when libraries that define similar globals to Node are present. A simpler solution to this would be to load Faye before QUnit, so that the top-level environment is not modified when Faye loads.

This is good practice in general since most test frameworks modify the top level in some way, and it's better to load all your app code before that happens to avoid accidentally depending on behaviour introduced in the test environment.

**Comment by jcoglan** [comment]
@molefrog @chetang Did you have any thoughts on my last comment?

**Comment by molefrog** [comment]
I personally can't give any general answer to this, because my problem was quite specific: we use Faye in the code that can be embedded on a page (sort of external widget, I would say). The client had inserted our widget on his page and somehow forgot to remove QUnit (I think it was on in H5BP by default). Unfortunately, we don't we have direct access to his page, so the only solution I could made up was to make CommonJS detection more strict by considering that `module` object has `exports` property (which is false in case of QUnit).

**Comment by jcoglan** [comment]
I'm going to close this since it sounds like an accident in usage rather than a bug that need fixing on this end. Thanks for your feedback.

**Comment by arung-ideas2it** [comment]
Iam facing the same issue in Mean.io where i executed some test cases in jasmine
