### ISSUE TITLE
Documentation on using Faye as Rack Middleware

### ISSUE THREAD

**Issue by TheNotary** [faye/faye#367]
I've been researching for the past couple days and am seeing a lot of old documentation that doesn't work for the new Faye, and small 'hints' that faye can be used as rack middleware so that there's no longer a need to run Faye in a separate thin instance.  Is that the case?  If that's possible, is there any way we could get some documentation on doing that?

**Comment by jcoglan** [comment]
Faye has always been usable as Rack middleware from its first release; the documentation is at http://faye.jcoglan.com/ruby.html.

Is there something we should add to those docs to make this clearer? Which documentation are you referring to that doesn't work? I try to keep Faye's APIs stable, so if there is example code out there that doesn't work then I'd like to know, in case it's an accidental break that I can fix.

**Comment by TheNotary** [comment]
It's good to hear from you and btw, thanks for this gem.  I'm in the process of extracting my chat code out of a rails site into it's own repo where it can be easier to learn from.  Yesterday I did a lot of trial an error after pasting in snippets from the page you linked.  I think my impediment stems from the fact that there's a lot of little things that all need to go right for it to work (the server needs to be configured right, the client needs to connect to the server right, the client needs to be setup to actually echo the messages it receives properly, etc).  

Also this will (hopefully) be my first manually configured middleware, and it's a little unclear where to put things.  Ideally someone like me first coming to this project would like to see a stand alone rails app that shows where to put extension code, what the config.ru should look like, and the command to start everything, and then some client.  

I just finished putting together an isolated repo that shows how the version of faye that uses the listen method works.  I think using the latest version of faye throws a fatal error, a link to github, and then, in my case, I wandered about the internet for a long while trying to figure out how to boot it as middleware.  

https://github.com/TheNotary/faye_ruby_example

**Comment by TheNotary** [comment]
I've started a repo for rails that would use the new rackup method.  When using middleware, do you still need to start the rails server and the faye server separately or will it ultimately work with one command like `rackup`?

https://github.com/TheNotary/faye_rails_example

**Comment by TheNotary** [comment]
I just pushed a final commit to my demo repo, and have everything working with the up to date version of faye.  

I used config/application.rb to use faye as middleware and am able to boot rails normally (though use -e production because of the middleware that breaks faye).  I also dropped in a simple faye extension into app/middlewares.  

If this seems like a sensible configuration, I think it's worth noting it somewhere.  I've been putting faye off for the longest time because of configuration uncertainties.

**Comment by jcoglan** [comment]
There are four reasons I don't specifically document usage with Rails:

* The Rails APIs are historically unstable and change a lot on major releases, and I don't have the resources to track these changes
* The documentation as it stands ought to be sufficient for use with Rails, because Rails is just a Rack app
* Rails obfuscates many things it's built on, creating uncertainty over whether things belong in `config.ru` or `config/application.rb` when it doesn't matter and there should be one interoperable place to do things
* I usually advise people not to run Faye and Rails in the same process for a variety of reasons

Given that I don't have the resources or inclination to maintain Rails-specific documentation, I think third-party places like blogs, stack overflow and the wiki are better places for this sort of thing. I'd encourage you to add any information you find useful to the [wiki](https://github.com/faye/faye/wiki).

**Comment by TheNotary** [comment]
I couldn't agree more with your points about rails, it's been a long arduous beta period with no end in sight ;)  I'll drop a link to the repo in the wiki in the hopes someone finds it helpful.
