### ISSUE TITLE
Force disconnect from server

### ISSUE THREAD

**Issue by rauhryan** [faye/faye#375]
Howdy, 

I have a quick question, is there a way to force all connections to disconnect from the server?

We moved our faye server to a seperate sub-domain and the old connections are endlessly trying to reconnect. We can't force our users to refresh their browsers in order to get the new connection, is there a middleware or some type of response we can return that will force the js client to disconnect?

Thanks

**Comment by jcoglan** [comment]
You could write an outgoing extension that, when it saw a `/meta/connect` message, sets `message.successful = false` and `message.advice = {reconnect: 'none'}`. You'd need to make sure this was only sent to old clients, otherwise no clients will be able to connect at all.

**Comment by jcoglan** [comment]
Actually I'm not sure that will have the right effect; it stops the client sending new messages, but any existing failed messages will still be retried. You need to force the client to call `disconnect()` or unload the page, so that the client drops whichever transport it is using and the retries stop.

**Comment by jcoglan** [comment]
Is this still an issue or can I close it?

**Comment by jcoglan** [comment]
I'm going to close this because of the lack of responses, but if it is still a problem then please do re-open it :)

**Comment by karneaud** [comment]
@jcoglan would I be able to get a bit more clarity on this subject? 

I want to close a connection on the **browser client** side where the browser client mostly **publish** and is not **subscribed**

How can I **"force"** the disconnection?

**Comment by jcoglan** [comment]
@karneaud You can't "force" any client to disconnect unless you've explicitly put measures in place to do so, e.g. requiring an authorization method that you can revoke dynamically. You need to have written extensions that allow you to do this, the Bayeux protocol does not provide any way of doing it out of the box.

**Comment by rauhryan** [comment]
I was able to write a simple extension to "force" disconnections. 

https://github.com/huboard/huboard-web/blob/master/vendor/gems/faye_extensions/lib/faye_extensions/disconnect.rb

I had a very unique use case to need this extension, so I don't think it would ever be useful to anyone else. 

My use case was that, we self hosted faye within the same ruby on rails application by mounting the faye engine as a middleware. This method proved to be more pain than it was worth, it caused various memory problems as well as through off our analytics and metrics because our socket connections were open for so long. 

We moved our websocket server into a microservice on a separate subdomain and needed a way for existing faye connections to force close when we wanted to transition from `app.com/faye` to `faye.app.com` after a few week I'm not even sure we need the middleware anymore as the problem "fixes itself after a given time"

Hope this helps

**Comment by karneaud** [comment]
@rauhryan  hmmmmmm....your scenario seems to have a similar intent as the one I want to do now. I'm also using faye as a middle service on nodejs. Though my expected traffic is going to be very low....It needed to be such that it was not going to be a "multi user" service. So i have to make sure the users would be immediately disconnected before another could connect otherwise it could cause a sort of "hijacking". I will look at your extension and try it out. Though I think I would need to elaborate a bit on your extension. Good starting point though


Thank man!
