### ISSUE TITLE
Establishing a tunnel via proxy server failed.

### ISSUE THREAD

**Issue by alexandrevicenzi** [faye/faye#376]
Hi,

I'm testing WebSocket through proxy and sometimes I get this error:

`WebSocket connection to 'ws://foobar.com/rtc' failed: Establishing a tunnel via proxy server failed.`

I'm using Squid 3.5 as an explicit proxy and the scenario is:

If squid kicks websocket connection in the begging of connection faye fallback to long-polling, but if I can connect using websocket and after connected squid kicks websocket connection, faye can't connect anymore to the server I get this error forever.

It's looks like that faye can't switch to another protocol in this case. Should faye fallback to another protocol?

**Comment by anubiann00b** [comment]
Same problem here.

**Comment by jcoglan** [comment]
So, Squid allows the WebSocket to connect successfully, but then later terminates the connection, and then allows no further new connections? Is the first connection able to send/receive messages for a time?

Clearly Squid implements enough of WebSocket for the `onopen` event to fire and for Faye to assume it will work, but it's breaking later during the connection. Do you know any more about why those connections are refused?

Have you tried using [websocket-driver](https://www.npmjs.com/package/websocket-driver) to connect to Squid and monitor the data it sends back? Sometimes monitoring the low-level protocol traffic reveals why something is not working.

**Comment by alexandrevicenzi** [comment]
@jcoglan, I'm not worried about Squid, but the main question is: Why Faye don't fallback to another protocol in this scenario? Faye assume that if connect through WebSocket in the first time, it must keep using WebSocket forever.

About Squid, I'm changing some configs during the connection. Sometimes this happens in the real world.

**Comment by jcoglan** [comment]
It doesn't fall back because its transport negotiation is not based on 'falling back' but on upgrading. It begins by using `XMLHttpRequest` and then upgrades to WebSocket if the server advertises support for it, the relevant browser APIs are present, and a connection can be established.

This is actually the first time anyone's reported a scenario to me where a server's WebSocket support is unstable, though of course this could always happen in theory when servers are deployed, restarted, etc.

The problem is that accommodating this would make the client more complex and more chatty. Say your are using the WebSocket transport, and then it suddenly fails to send a message. Currently, we hand the message back to the `Dispatcher` and that tries the request again after a timeout.

To fall back to another transport, we'd need to keep a 'stack' of transport objects, rather than the single reference we have at the moment. If the dispatcher received a failure from one transport, it could try the next one down the stack. It could track which transport was last used to send each message and try the next one down on the next attempt.

This model sounds appealing but has a number of problems:

* What do you do with in-flight messages when a `selectTransport()` call changes the set of available transports? Does it push the new transport on the stack or replace the old stack? How does this interact with connection management?
* What if every transport on the stack fails? Do you keep trying with the lowest one, or go back to the top?
* What happens to new messages entering the dispatcher? Are they aware that the topmost transport has failed and not even bother trying with it?
* How do you find out if a failed transport is usable again, given that it might not be possible to distinguish the server being down, from the client's network connection being down, from the server being broken? Can you discover this without sending messages to the transport and wasting latency on failed calls? (This depends on the transport's implementation details, so it will leak into the dispatcher. Some transports take a very long time to report a failure.)

If the WebSocket transport stops working, it is probably impossible in general for the client to tell why it's not working or if it will come back. Depending on the reason and the retry strategy, it may add a lot of latency to message sends to re-establish the WebSocket transport, given the client wants to use the best transport available.

Usually, from a latency point of view, the best transport available is the transport you have. Trying other transports is expensive. If I knew my WebSocket server didn't work very well, I would disable the `websocket` transport on the client side and stop it wasting time attempting to use it.

**Comment by jcoglan** [comment]
@alexandrevicenzi do you have any feedback on the last comment I left?

**Comment by alexandrevicenzi** [comment]
Hi, sorry for the late reply.

I think you're right, it's a complex environment.

About the other transport, we current use long polling, but we want to add WebSockets to improve user experience.

As this error needs an strict environment to reproduce I think we can close this.

**Comment by jcoglan** [comment]
I think you've identified a legit issue but I just don't know a good way to solve it at the moment without generating a lot of chatter on the network. Given nobody else has reported anything like this, I think it's low-priority, but I will think it over for a future release if I have time.
