### ISSUE TITLE
"Uncaught TypeError: Cannot read property '_state' of undefined" error in Chrome 43

### ISSUE THREAD

**Issue by javan** [faye/faye#394]
I haven't spent much time investigating, but after bumping from Faye 1.1.1 to 1.1.2 I started getting this error in Chrome 43 on Mac and Windows. Appears to be `Promise` related.

**Comment by AleksandrLeontev** [comment]
The same error

**Comment by jcoglan** [comment]
@javan @AleksandrLeontev Do you have a stack trace or some example code that triggers this error?

**Comment by javan** [comment]
Unfortunately (or fortunately), I can't reproduce the error any more. I was seeing it in the console when running [Trix](https://github.com/basecamp/trix)'s QUnit test suite. Trix includes [this Promise polyfill](https://github.com/taylorhakes/promise-polyfill), which we've since updated to a newer version, and I'm on Chrome 46.0.2490.80 (64-bit) now. From my end, I'd consider the issue closed, but I'll let you decide if you want to close it since @AleksandrLeontev chimed in too.

**Comment by jcoglan** [comment]
I will close the error then, but please re-open if you find a repro case, a stack trace, or you have example code I can use.

**Comment by henrikbjorn** [comment]
I get this in my React project:

<img width="809" alt="skaermbillede 2016-03-02 kl 16 16 27" src="https://cloud.githubusercontent.com/assets/19725/13464593/261dd884-e092-11e5-979b-158c44189a42.png">

It occurs in all browsers, Safari, Chrome, Firefox

**Comment by henrikbjorn** [comment]
It would seem that when Faye does `new Promise()` it uses the global provided by the browser or a Polyfill, and because of that, the property isn't available.

**Comment by jcoglan** [comment]
@henrikbjorn I'm going to need specific code to reproduce this error in order to make any more progress on it. Also, how did you determine that Faye is using the built-in `Promise` class rather than its own implementation?

**Comment by henrikbjorn** [comment]
@jcoglan I created a gist here https://gist.github.com/henrikbjorn/b25363fa82a303e9631f

The output from the Chrome DevTools Console is attached.
![skaermbillede 2016-03-03 kl 10 25 21](https://cloud.githubusercontent.com/assets/19725/13490009/5bcb3858-e12a-11e5-8962-b9e3cf87b99b.png)

Using the global Promise object was a theory, but it doesn't seem like thats the issue. There is one subscription that fails, if that is removed the error disappears.

**Comment by jcoglan** [comment]
@henrikbjorn Thanks a lot for the test case. The issue is now fixed as of https://github.com/faye/faye/commit/e7e6c975a28e748770325c14e0ead09a3d747bb9.

**Comment by jcoglan** [comment]
Just letting you know 1.2.0 has been released: https://groups.google.com/forum/#!topic/faye-users/_0kTHXciUGs

**Comment by bmatcuk** [comment]
It looks like the 1.2.x client has problems communicating with a 1.1.x server, so... to anyone who's stuck on the 1.1.x branch as I am, I've backported this fix to 1.1.2 to create a sort of "unofficial" 1.1.3: https://github.com/bmatcuk/faye

I've also included a branch called [1.1.3-built](https://github.com/bmatcuk/faye/tree/1.1.3-built) that contains the built output (ie, the 1.1.3-built branch is what would be in npm if this was an official 1.1.3 release). This makes it easy to include the "1.1.3" branch in your package.json with something like:

```javascript
{
  ...
  "dependencies": {
    ...
    "faye": "bmatcuk/faye#1.1.3-built"
    ...
  }
  ...
}
```

I haven't thoroughly tested, but it looks like it's working... it does pass the automated tests.

**Comment by jcoglan** [comment]
@bmatcuk Can you describe what problem you're having using the new client and provide some example code? Incompatibilities like that are considered regressions and I'd like to fix it.

**Comment by bmatcuk** [comment]
I'm afraid I can't be much help as I'm in a bit of a crunch right now... it was easier for me to cherry-pick this commit into the 1.1.2 branch than to debug the issues with 1.2.0.

I can tell you our server is running v1.1.2 in ruby with a custom extension and I've monkeypatched some of the Faye Engine code (which is why I don't want to upgrade the server to 1.2.0). If I tried using the 1.2.0 client in my browser, I didn't get an error, but it halted my script which means it was probably throwing a error in a promise that's getting silently eaten.

Like I said, I didn't spend much time investigating because I've got about 3 weeks of work I need to finish in the next 3 days, so... it's entirely possible that the problem is on my end... did the client API change at all? Maybe my code is calling a function that no longer exists or got renamed in 1.2.0? I dunno.

Maybe I'll investigate further in a couple weeks when things have died down... Sorry.
