### ISSUE TITLE
No route matches [GET] "/assets/faye-browser-min.js.map")？

### ISSUE THREAD

**Issue by liguangsong** [faye/faye#399]
ActionController::RoutingError (No route matches [GET] "/assets/faye-browser-min.js.map"):

**Comment by jcoglan** [comment]
Could you explain what you're doing to trigger this error, and provide a small example of how to reproduce it?

**Comment by jcoglan** [comment]
The most common causes of this error are:

* Copying `faye-browser-min.js` into a project but not copying `faye-browser-min.js.map` and `faye-browser.js` along with it
* Loading the client from the Faye server using `/faye.js` rather than `/faye/client.js`

I'm going to close this issue due to lack of feedback but if you are still stuck on this issue then please re-open it and let me know :)
