### ISSUE TITLE
Prevent duplicate channel subscription by the client.

### ISSUE THREAD

**Issue by nsantiago2719** [faye/faye#412]
I don't know if this is issue in faye or not but I'll try to explain it. I have a Web application and I'm using Ror for the backend , turbolinks are enabled. Now on the homepage it will automatically let you subscribe on a channel, but if I click the home link again it will subscribe again on the default channel. The problem here is if I send a message on the channel I'll see a duplicate entries but if I refresh the page the duplicate entries won't show. So are there any method if faye that if the client is subscribe in the channel already it will just refresh the subscription?

**Comment by jcoglan** [comment]
I'm not sure I understand your situation. Are you creating a new client and subscription each time you visit the home page, or are you re-using the existing client and calling `subscribe()` on it again?

Either way, Faye won't stop you doing that -- it deliberately allows you to subscribe multiple times to the same channel. It can't tell that two functions you pass to it are really the 'same code'. If you're creating a new client every time it definitely can't detect that because each client will only have one subscription anyway, and if you're creating multiple clients you'll soon run out of TCP connections anyway.

You need to keep the same client instance around between 'page views' and make sure you only subscribe when the client is first created. Or, you need to tear down the existing client by calling `disconnect()` and make a new client on the next page.

**Comment by silvercrow27** [comment]
Ok, for the mean time I'll try the disconnect() every time I go to the other page.

**Comment by silvercrow27** [comment]
Hello. I haven't solve this problem yet. So I think it's better if I include a picture. As you can see there is a chatbox on the right side. If I go to the other page by click a link the menu and chat  it will duplicate the same message.
![vslx1](https://cloud.githubusercontent.com/assets/6946531/11806340/511a657a-a34d-11e5-9817-f999bd580ec7.gif)

**Comment by jcoglan** [comment]
I understood the issue from your first description. The most likely cause is that you are either:

* creating a new client on every 'page' load without disconnecting/unsubscribing the existing one
* deliberately reusing a client but calling `subscribe()` on every 'page' load, producing duplicate listenters

**Comment by silvercrow27** [comment]
Yes, but when I tried to unsubscribe on page load it says that it doesn't exist.

**Comment by jcoglan** [comment]
I'm not sure what you mean by "it doesn't exist". Exactly what code are you running to unsubscribe, and what error do you get?

**Comment by jcoglan** [comment]
Do you have any more feedback on my last comment, or should I close this issue?

**Comment by nsantiago2719** [comment]
sorry. I forgot to close the issue. my bad
