### ISSUE TITLE
Getting a routing error with the faye/client.js 

### ISSUE THREAD

**Issue by yanhackcode15** [faye/faye#425]
I got faye working on my local env but all the sudden, it's spitting out this error:
POST http://localhost:3030/bayeux net::ERR_EMPTY_RESPONSE
faye.self-6823ebf854fb1d2d75757d5eb2fbaecc5863cccae77e3b5cefb2221905c240c3.js?body=1:3 

I'm running my rails web server on port 3030 and faye on port 9292. 
I've never seen this error before and couldn't find anything online about it.

**Comment by yanhackcode15** [comment]
On rails server logs, it's complaining about no route found:

Started POST "/bayeux" for 10.0.2.2 at 2016-02-24 20:37:28 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"

ActionController::RoutingError (No route matches [POST] "/bayeux"):

**Comment by jcoglan** [comment]
This seems like an integration issue rather than a bug in Faye specifically, but beyond that I'm not sure what to suggest. Faye requests should not be routed and handled by Rails.

Have you made sure Faye and Rails are running as separate servers? Have you checked which server your client is connecting to?

**Comment by jcoglan** [comment]
Did you have any further feedback on this issue, or should I close it?

**Comment by yanhackcode15** [comment]
Yep. Can close.

- Yan
