### ISSUE TITLE
Unit testing with angular

### ISSUE THREAD

**Issue by anandi2i** [faye/faye#426]
Iam using angular and jasmine for my unit test case execution and i need to call the faye services in my test spec

Is there anything to do so ?

**`Faye.publish('/broadCastUpdatedActions', {
          content:"content"
 });`
`Faye.subscribe('broadCastUpdatedActions', function(data) {
         console.log(data);
});`**

**Comment by jcoglan** [comment]
This seems like more of a question than an issue, and I see you asked on the mailing list. I personally don't know enough about Angular or Jasmine to be sure what the question means, sorry I can't be more help.

I'm going to close this issue since it's not something I can action; I recommend following up on the mailing list with more information about your problem, or consult the Angular and Jasmine communities, or ask on Stack Overflow.
