### ISSUE TITLE
SyntaxError: Unexpected end of input in EventSource.n.onmessage

### ISSUE THREAD

**Issue by squadette** [faye/faye#427]
We observe persistent error which looks like this in Sentry:

SyntaxError: Unexpected end of input in EventSource.n.onmessage
browser = Chrome 48.0

```
{snip} iled"),n.close())},n.onmessage=function(e){r._receive(JSON.parse(e.data))},this._socket=n},close:function(){this._socket&&(this._socket.onop {snip}
```

(sorry, this is all I got, but i hope that this is enough.  At least it should not die when receiving junk from EventSource. I don't even know what is in this EventSource message.

I "solved" it by disabling "eventsource", but probably this needs investigation (which I can help with).

Thanks,

**Comment by jcoglan** [comment]
I'd need to know the value of `e.data` in this scenario to know what's causing the error.

It's supposed to be a valid JSON string, the same as is sent over WebSocket connections, but the design of the EventSource protocol means the client may read a partial message that's sent before the connection is terminated.

**Comment by squadette** [comment]
Okay, I added debugging and deployed it live.  TL;DR: the message looks like JSON which abruptly ends and there is "retry: 5000" string attached to its end.

This is the string content of e.data:

```
[{"channel":"<my channel id>","data": <...my JSON message, which ends abruptly and then ...>retry: 5000
````

I have a very strange observation: for some reason this bug only happens for Turkish users of my site (I checked several dozens of errors and they're all like this).  Also, the browser is always reported as Chrome 48.0, with OS Windows 7, 8 or 10.

It was gathered by the following patch:

````
     socket.onmessage = function(event) {
-      self._receive(JSON.parse(event.data));
+      try {
+        self._receive(JSON.parse(event.data));
+      } catch (e) {
+        Raven.captureException("Broken EventSource JSON: '" + event.data + "'");
+        Raven.captureException(e);
+        throw(e);
+      }
````

I'm disabling eventsource for now, but I can debug it again if needed, it could be reproduced easily.

Thanks,

**Comment by jcoglan** [comment]
Are you able to find out the full text of messages are triggering truncated `EventSource` messages?

It's inherent in the EventSource protocol that a message may be partially sent and the client is not able to tell. WebSocket and vanilla HTTP do not have this problem so using them instead of EventSource seems like a reasonable fix in the mean time.

**Comment by squadette** [comment]
the full text of messages is just the JSON I'm publishing.  I don't see anything suspicious, and the byte lenght is also varying and I don't see obvious patterns.

Well, yes, disabling eventsource works perfectly.   I don't even know what advantages EventSource has.

Thanks!

**Comment by jcoglan** [comment]
> the full text of messages is just the JSON I'm publishing

Sorry, I meant do you have a specific example of a message that breaks EventSource and causes your JSON to be truncated? i.e. where the message in the `onmessage` handler is not the same as the message you published.

The advantage of EventSource is that it's a simpler protocol than WebSocket and since it's closer to streaming HTTP than WebSocket's bidirectional binary protocol, it gets through HTTP proxies more easily. WebSocket connections are frequently broken by proxies and firewalls.

**Comment by jcoglan** [comment]
I've added code in a8727f0a692a1d29ca60274d9ca6e2de9ef2cbbf to handle cases where invalid messages arrive via EventSource.

**Comment by squadette** [comment]
@jcoglan thanks!  but what will happen?  will the message be discarded or somehow retried?

**Comment by jcoglan** [comment]
With the EventSource transport, messages arriving over the socket are messages from other clients, rather than server replies to the client's own messages. The client has no way to detect that it should have received such messages, and they will be lost.

You should implement something in your application to guard against this if it's a problem for you. This kind of error can in principle happen to any transport, where the server sends the message but it's lost in transit on its way to the client.
