### ISSUE TITLE
High Availability and Scalability Recommendations

### ISSUE THREAD

**Issue by dhakadamit** [faye/faye#432]
We are a real-time tick by tick data provider for Financial Markets. We use Faye for the distribution of this information in real-time.

**Current Stats:**
80K-150K ops/second with only 1K-3K writes/second
3K-5K connected clients

**Expected Growth:**
In the next six months, we expect the following traffic
1M-5M ops/second with about 10-50K writes/second
100K-500K connected clients

**Current Architecture:**
Redis - Single Master Setup
Faye - 2 Write Masters and 4-6 Read Slaves 
(All are 8GB Linode Instances)

**Future Solutions in Mind:**
1) Move to High CPU instances
2) Setup Redis in Cluster Mode

**Problems and Suggestions:**
1) We noticed that Faye could not work with **Redis setup in Cluster Mode**. Is it possible currently? 
2) **Frequent disconnects**. How do we ensure that the connection holds on?
3) **Connection hangs**. Websocket is open but no messages arrive for a second or two and then starts again. It give a sluggish feeling.
4) Any other suggestions are most welcome. 

We would be glad to get any help. Thanks in advance.

**Comment by jcoglan** [comment]
I tend not to give out specific recommendations in this area since that's usually better done by someone who actually works on your stack. However I will mention a few things:

> 1) We noticed that Faye could not work with Redis setup in Cluster Mode. Is it possible currently?

The [faye-redis](https://gtihub.com/faye/faye-redis-node) that I created is under-maintained, since I don't have much time to work on it and I'm not that knowledgeable about newer Redis features.

However, in order to remove me as a bottleneck, the engine is pluggable, and [other engines are available](https://github.com/faye/faye/blob/a99192e7823dcf628b1a3e20a6aa738ea3027ce1/site/src/pages/node/engines.haml#L20-L25). If neither of those is suitable, I would consider writing your own.

> 2) Frequent disconnects. How do we ensure that the connection holds on?

It depends what you mean by 'disconnects'. Do you mean clients are using HTTP polling, or are they using WebSocket and disconnecting, or is the 'logical' connection (i.e. the Bayeux session) frequently timing out?

**Comment by jcoglan** [comment]
I'm going to close this issue because I don't think there's any more for me to do here and I'm trying to close up a release. If you have any more questions, do please open another issue :)
