### ISSUE TITLE
Message received promised

### ISSUE THREAD

**Issue by karneaud** [faye/faye#434]
if a client publishes a message to a channel and no one is subscribed to the channel......is the message still received?

If no then why would I not get a failed message on a promised subscription when I published a messaged to a channel no one is subscribed to?

**Comment by jcoglan** [comment]
I assume you're referring to this API:

```js
client.publish(channel, message).then(function() {
  console.log('success');
}, function() {
  console.log('failure');
});
```

When this code prints `success`, it means it was received and considered valid by the server, regardless of how many clients it will be forwarded to. `failure` means the server considered the message invalid, not that the message was not sent to any clients.

The client API does not provide any feedback about how many clients the message was sent to, and the underlying Bayeux protocol does not provide such information.

**Comment by karneaud** [comment]
Is there any way we can get a "read receipt" from clients who have received it?

I guess the client can always publish a notification back to the source but I'm just thinking something builtin so we can hook into

**Comment by jcoglan** [comment]
No, the Bayeux protocol does not require clients to confirm receipt of messages. It would make the protocol much more chatty, and would be prone to its own errors. A client may receive a message but fail to send a receipt to the server and back to the sender.

I usually recommend that you address such concerns in the application layer, since each application's needs in this area can be quite different.
