### ISSUE TITLE
v1.2.0 seems to have introduced breaking API changes

### ISSUE THREAD

**Issue by stemail23** [faye/faye#444]
I'm using faye module indirectly (via jsforce module). It seems to me that v1.2.0 of faye has introduced breaking API changes, as `Faye.Transport` does not seem to exist anymore. I haven't dug deep, but it looks like this has broken semver, and this should have been a major version bump.

On a related topic, I notice that faye module uses `"*"` versioning for several dependencies (asap, csprng etc.). This is bad form and means that the faye module itself would be broken by a major version bump to any of those dependencies. I would suggest locking the major version at least of dependencies.

**Comment by jcoglan** [comment]
I'll caveat this by saying my modules don't explicitly follow semver, and that I believe it provides much weaker guarantees than those that are claimed for it. However, I try to follow the spirit of semver, roughly, but not to the letter. For example, I will sometimes use a major version bump when a substantial amount of the internals of a project are rewritten, even if there were no API changes. Major versions can indicate things other than 'breaking changes' and I actually strive for backwards compatibility in all my releases.

In this case, I don't count hiding `Transport` as an API change because that class isn't public, meaning, it's not in the documentation. I realise this might be an odd definition of 'public' but since JS has no visibility control system, documentation is what I use to indicate the intended API for a module.

If you still need to access `Transport`, you can now access it using `require()`:

```js
var Transport = require('faye/src/transport/transport');
var XHR = require('faye/src/transport/xhr');
```

Requiring deep into a module's source tree should be enough of a cue that you're using something private and should be aware it might break.

As for the dependencies... I take the approach that libraries should have at permissive a dependency range as possible, so that users can upgrade their transitive dependencies without requiring all the intermediate deps to put out releases. This reduces my workload and makes it easier for users to deploy performance and security improvements. I make a call be looking at the release policy and history of each dep I take on, and in this case, I wrote most of the deps of `faye`, so I'm confident I won't break them.

**Comment by stemail23** [comment]
Thanks for the reply. As I mentioned, I'm only consuming faye indirectly as a dependency of jsforce. If, as you mention, Transport is intended as a private element, then your argument for a minor version bump in this case is valid, and I make no judgement on the jsforce developer's choice of use of your library.

As regards your general observations on semver, and robust dependency declarations, we'll just have to agree to differ.

**Comment by jcoglan** [comment]
It looks like `jsforce` is digging deep into Faye's private APIs, e.g.:

https://github.com/jsforce/jsforce/blob/844d3bfde5233c0ead000428801cb4b41bb3a57e/lib/api/streaming.js#L130-L143

Code like this wouldn't even be safe against patch releases.

**Comment by stemail23** [comment]
It's a fair point, it seems like jsforce is attempting to leverage some of the deeper lying, non-public, functionality of your modules, which is the root cause of the issue. I also notice that the author has now patched the crash in his code caused by this approach. Happy for you to close this issue as answered.
