### ISSUE TITLE
Fallback / alternative connection [Browser]

### ISSUE THREAD

**Issue by bato3** [faye/faye#470]
Is there a simple way to change the endpoint during a connection?
(In the case of the unavailability of a particular destination, missed connections or frequent breaking the connection)

Is there a simple way to get channel subscriptions? (I method to cancel all subscriptions?)

**Comment by jcoglan** [comment]
No, there's currently no way to change the endpoint a client is connected to. The usual approach to this is to listen for `transport:down` events and handle them by disconnecting the current client and creating a new one on a different endpoint, if that's what you want. The decision to switch endpoints usually requires information that's outside the scope of the Bayeux protocol, which is why Faye makes the user make these sorts of decisions.

Cancelling all subscriptions is accomplished by calling `client.disconnect()`. After this the client will become unusable and you'll need to create a new instance if you want to connect and make new subscriptions.

**Comment by bato3** [comment]
@jcoglan Thanks for reply.

Is there a simple way to get list of channel subscriptions?

**Comment by jcoglan** [comment]
No; that's something you should keep track of yourself.
