### ISSUE TITLE
Why do you remove the client id?

### ISSUE THREAD

**Issue by Xsmael** [faye/faye#474]
Hi, was finding a way to identify the publisher of a message at client side, and i just notice you deliberately removed it. it sounds a bad idea, no alter my copy of the library to get the work done, plus i think you must have done it for a good reason. so i would like to know why 

```
 deliver: function(message) {
    delete message.clientId;  // <-------------------------------------------
    if (this.socket) return this.socket.send(message);
    this._inbox.push(message);
    this._beginDeliveryTimeout();
  },

```

**Comment by jcoglan** [comment]
It's a security measure. Knowing the ID of a client allows you to connect to the server and receive any messages routed to that client, meaning they won't be received by the intended recipient.

It also means you'd be receiving all messages from channels that client is subscribed to. The original client may have had to authorise with the server in order to be granted the subscriptions it has, and if you have its client ID, you can poll for its messages without having had to pass the same authorisation checks as it did.

Therefore, clients are prevented from seeing each other's IDs. If you need to identify the application session that a client is acting on behalf of, you should implement that in the application layer.

**Comment by Xsmael** [comment]
Okay
