### ISSUE TITLE
Ping vs Timeout?

### ISSUE THREAD

**Issue by mspensieri** [faye/faye#487]
I'm trying to understand the relationship between the `ping` option and the `timeout` option, and how they relate to websocket connections. We are trying to optimize battery usage on mobile clients by minimizing the amount of time spent using the  network radio, and tweaking the `timeout` value seems to have an effect on this.

I've recently come across the `ping` option, which is documented as such:

> ping – (optional) how often, in seconds, to send keep-alive ping messages over WebSocket and EventSource connections. Use this if your Faye server will be accessed through a proxy that kills idle connections.

We do indeed have a proxy that kills idle connections after 55 seconds, so this seems to be the option I'm looking for. However, I'm not sure how the `ping` value is actually affecting how often frames are sent over the websocket connection - it seems only `timeout` changes this.

I've included an example screenshot below, using the standard javascript client library. In this example, my `timeout` is set to 25s, and my `ping` is set to 45s. We can see that every `timeout / 2` seconds, the js client sends an empty array `[]` frame, and receives one back. Every `timeout` seconds, a `/meta/connect` message is sent from the server, and acknowledged back by the client.

<img width="998" alt="screen shot 2017-10-17 at 9 01 50 am" src="https://user-images.githubusercontent.com/2286852/31666413-24bf4df4-b31a-11e7-8232-74f30eb93f79.png">

How does the `ping` value factor into this loop? And how can we make it so that it only sends frames every `ping` seconds, rather than every `timeout` or `timeout / 2` seconds? I'm also curious why the `/meta/connect` message is polling at all? I couldn't find any documentation on why that should be the case, rather than just sending an initial message when the connection is established.

The obvious answer to this problem to increase the `timeout` to match our desired ping interval, however the `timeout` value affects other transport types as well. Our web server times out requests if the server does not respond after 30s, so for the long polling transport (for example), the `timeout` needs to be lower than 30s. But for the `websocket` transport we'd like to take advantage of the 55s idle connection timeout and save on battery usage.

Any information you could provide would be greatly appreciated.

**Additional Context:**
For the examples above, I am demonstrating the behaviour using the client library in this repository, however we are also using https://github.com/m1entus/MZFayeClient, which I realize is not necessarily affiliated with this project but I'm mentioning it just for some context. That library does not implement the empty array ping, it seems to rely solely on the `/meta/connect` ping every `timeout` seconds, which is initiated by the server. We are trying to achieve the energy efficiency savings on iOS using this library.

We are using the node version of this library for the server-side implementation.

**Comment by jcoglan** [comment]
There are three distinct concepts here:

* `timeout` is a setting in the Bayeux protocol. It's the amount of time that a server waits before replying to a client's `/meta/connect` message. This message is used to poll the server for new messages; the server responds as soon as  there are new messages for the client, or after `timeout` seconds have elapsed, whichever is sooner.
* `ping` affects the WebSocket protocol. It instructs the server to send WebSocket ping frames to the client at the specified interval. These aren't data frames so you won't see them in the console. This feature tries to prevent proxies shutting the connection down from the server side.
* The WebSocket transport sending empty message payloads (`[]`) to the server at `timeout/2` intervals, which prompts the server to respond in kind. This is done because in some cases, WebSocket connections can be interrupted by the browser fails to report this. This mechanism allows Faye to detect such sockets and reconnect.

> I'm also curious why the /meta/connect message is polling at all?

For socket-based transports, this message is not required to poll for messages but it is still needed as a heartbeat mechanism. If Bayeux servers don't see such a message arriving periodically from a client, they terminate the client's session.

**Comment by mspensieri** [comment]
Thanks for the explanation

> For socket-based transports, this message is not required to poll for messages but it is still needed as a heartbeat mechanism.

So knowing this to be the case, is it safe to say that for the websocket transport, the `ping` interval could be used instead of the `timeout` interval for the `/meta/connect` heartbeat, and everything would still work as expected?

**Comment by jcoglan** [comment]
To answer your last question, we should not do this: the client must not have multiple `/meta/connect` requests in flight at a time, and so should not send this message more frequently than the server has told it to. In particular it should not send a `/meta/connect` message until it's received a response to the last one.

We have actually had to remove the "client-side ping" technique of sending `[]` over the WebSocket connection, as it's not accepted by the reference implementation of Bayeux.

Are there further questions you have about this, or can I close this issue?

**Comment by mspensieri** [comment]
You can close the issue, thanks
