### ISSUE TITLE
Can publisher check if subscribers are listening?

### ISSUE THREAD

**Issue by soumyaray** [faye/faye#491]
Thanks James for this gem of a gem :)

BACKGROUND: I have short-lived server-side workers that publish to a Faye server using POST requests (with appropriate channel IDs), and browser clients are subscribing to those channels. Typically, each channel only has one browser client subscriber. The publishing worker typically comes to life at almost the same time as the subscriber and works for several seconds, publishing progress reports, before closing.

PROBLEM: On occasion, my worker finishes its work very early and publishes all its messages _before_ a browser client has even subscribed – consequently, that browser client simply waits forever for messages that were long ago published but can no longer arrive.

Whats the best way for me to resolve this situation?  Can the publishing worker check if clients are subscribed before commencing work?  Can the browser clients check if any messages were published to the channel before they subscribed?

For now, my work-around is simply for the worker to wait a few seconds after completion and publish a last "done" message for any late coming subscribers.

**Comment by jcoglan** [comment]
Faye does not provide any way for one client to query the state of any other client or channel; doing so would more often than not lead to race conditions, and it's intended that you should just publish messages regardless of whether anybody is listening for them.

If your program relies on a client not missing events, then you need to add some persistence somewhere. This could mean one of several options.

One option is, you actually persist the state you need somewhere and then just use Faye to emit notifications that the data is changed, rather than to transfer the information itself. The client fetches the state from the server and reloads it whenever it gets a notification.

Another option also involves persisting state but continuing to use Faye to distribute it. There's a common pattern for a client to receive the latest state of a resource when it first subscribes to a channel, and then receive updates after that.

Third, you may want to keep all the stuff Faye gives you on the front-end for getting messages in the browser, but replace the backend implementation. I'm not sure how far you could push this but you could look at doing a custom [engine](https://faye.jcoglan.com/ruby/engines.html) that persisted messages per channel and allowed clients to receive recent messages, rather than the ephemeral in-memory per-client queue that Faye uses out of the box.

**Comment by soumyaray** [comment]
Thanks @jcoglan for laying out my choices — these are very helpful indeed.
