### ISSUE TITLE
Client is getting disconnected after some time

### ISSUE THREAD

**Issue by swati410** [faye/faye#492]
With the salesforce api version 37 and above client is getting disconnected while we subscribe to push topics and platform events in salesforce.
Following is the error seen in logs after which client disconnects.

```
incoming
{ clientId: '5rw1bxn4jzyed3vhbcjnpkwb2fsd',
  advice: { interval: 0, reconnect: 'none' },
  channel: '/meta/connect',
  id: 'k1',
  error: '403::Unknown client',
  successful: false }
```
We are using nforce node module to subscribe to topics which uses faye client to connect to salesforce.

**Comment by jcoglan** [comment]
This looks like correct behaviour on Faye's part. If the server sends `advice.reconnect = "none"` then the client is not supposed to send it any further messages.

**Comment by srihakum** [comment]
@jcoglan Yes that seems the right approach when server itself is saying not to connect again. However we do not get a transport:down event so that we could handle the logic for such cases.

**Comment by jcoglan** [comment]
You don't get a `transport:down` event because the transport layer is fine. That event is fired when the underlying network mechanism -- WebSocket, XMLHttpRequest, JSON-P, etc -- is showing signs that a request failed to get a response from the server. In this case, the transport layer is working fine, it's just the server is telling you explicitly not to connect any more.

I didn't build in any event for this because it didn't seem like there's a lot the caller can do. Certainly you can't create a new client immediately -- doing so would be equivalent to your existing Faye client ignoring the `reconnect: 'none'` from the server and continuing to try to connect to the server. I've also usually taken the line that you should not rely on the connection status in this protocol to ensure your app's correctness -- that should be built into the data modelling and protocols you build on top of this system.

If you do want to detect this event, my advice is to add a client-side extension that checks for messages from the server that contain `{advice: {reconnect: 'none'}}` and triggers whatever logic you want at that point.

**Comment by dhulke** [comment]
Salesforce expects an authentication header with a previously requested access_token to be sent, which we set right after creating the client. This token will expire eventually. When it does, salesforce sends a `{"channel":"/meta/disconnect"}` followed by a `"advice":{"interval":0,"reconnect":"none"}`.
The correct behaviour here would be to request a new token and reconnect. To do that, I need to track this reconnect none. It would be a lot simpler if I could do that using an event instead of an extension

**Comment by jcoglan** [comment]
Is this an ongoing issue, or can I close it, @swati410?

**Comment by jcoglan** [comment]
As I've not had a response to my last command, I'm going to close this issue, but please re-open it if it requires more attention :)
