### ISSUE TITLE
Faye not working while using https rails app and http faye app

### ISSUE THREAD

**Issue by manohar-nyros** [faye/faye#494]
Hi there,
I am having rails app and deployed in AWS EC2 with apache and unicorn. In this application I have used faye for messaging module.It is working fine with http application but Faye is not working while using https(ssl) for web application and http for Faye app.

In this situation are we really required https for both apps(web app and faye app)?
Please let me know.
Error:
The page at https://xxxx.xxxx was loaded over HTTPS, but requested an insecure script 'http://xxxxxx:9292/faye.js
   
Thanks in advance.

**Comment by alongley** [comment]
I've struggled a bit with the SSL side. I probably can't answer you directly, but I thought I'd post a comment just to jog other comments in an effort to add some clarity.

In simple terms, Faye opens a single port that you specify (8000 default) in either http or https mode. This means that clients will communicate properly with http://<server>:8000 or https://<server>:8000. It's designed to serve static html content if a browser accesses this url directly, and while I still don't understand it, if you request http(s)://<server>:8000/bayeux/client.js you magically get the faye client js code. This is because it serves non-bayeux requests with the contents of the /public directory, and requests to /bayeux, which are handled by the "bayeux interpreter", serve client.js from "somewhere"; I assume it's automagically compiled at some point.

In your case you are obviously requesting a script insecurely, http://xx:9292/faye.js. The browser is doing you a favor and letting you know you shouldn't do that. You should request https://xx:9292/faye.js, which would require that the server listening on 9292 is running SSL/TLS and designed to serve http requests over SSL/https requests (however you want to look at it).

I'm building a Faye cluster with a custom engine, a load balancer (probably an F5 device in production), and clients are web browsers running both a custom front-end abstraction api layer, then the faye client layer, to the LB and thence to the Faye cluster (storing state in Redis). In my dev environment, if I use haproxy, and an Apache virtual host to serve the front-end, and the front-end requests https://<server>:8000/bayeux/client.js, and then attempts to subscribe, I get browser issues about Access-Control-Allow-Origin cannot be '*' when Access-Control-Allow-Credentials is false. I have to edit faye/src/adapters/node_adapter.js and change Access-Control-Allow-Origin to https://<server>. Obviously I won't do this in production, I'm hoping that the F5 redirects secure requests externally to insecure internal requests, and just run the Faye servers insecure internally as they are not publicly exposed. But there are definitely details of SSL/TLS I don't understand.

**Comment by manohar-nyros** [comment]
Did you mean, Do I need to set up SSL for faye server also?

**Comment by alongley** [comment]
I don't know how to answer this. If you pass 'tls' as the second argument when starting faye e.g. node server.js 8000 tls, faye will open an https server on port 8000 instead of an http server on port 8000. If it starts an https server it will use the temporary security certificate (server.crt and server.key) to allow encrypted http communication for both traffic over bayeux and for the delivery of static content (the stuff in /public). In production you would not want to use the temporary security certificates.

Your original question is not precise enough for me to understand. Faye does not need to be running securely but if it's publicly exposed it would be extremely poor practice not to secure it. 

If the web app is running on AWS behind some sort of load balancer, and in turn communicating with Faye server, then Faye server is not publicly exposed and the web app should be able to communicate insecurely with Faye server. 

If the web app acts as a client to Faye you really should have Faye behind a load balancer or proxy. In this scenario you would have say a web app at https://1.1.1.1/app and it in turn would load https://2.2.2.2/bayeux/client.js (for example). 2.2.2.2 is a LB or proxy that accepts traffic on port 80 and in turn requests from the internal Faye server insecurely at 192.168.1.3:8000 or whatever port. From the browser's perspective everything is secure.

If the web app at https://1.1.1.1/app is requesting the client.js insecurely directly from Faye server e.g. http://3.3.3.3/bayeux/client.js that's a problem. It means traffic from your app to Faye is insecure. You've gone to the trouble of securing your app, therefore it has sensitive data, so you should also secure the messaging piece.

I'm not clear on what http://xx:9292/faye.js is, what that server is, what faye.js is, etc.

**Comment by manohar-nyros** [comment]
Could you show me sample cofig for setting Faye behind load balancer or proxy? I tried with proxy pass and reverse proxy pass. But I unable to make it.

**Comment by jcoglan** [comment]
Hey @alongley, thanks for helping folks with this question :)

Is this an ongoing issue, or can I close it? For the record, I've tried to arrange things so that Faye is not responsible for SSL concerns -- that should be handled by the app server that you use to run it, or by a reverse proxy like nginx or apache. However it does still cause some issues, so if there's something we can improve, I'd like to know.

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of responses, but please re-open it if you'd like to continue the discussion :)
