### ISSUE TITLE
websocket instance error handler

### ISSUE THREAD

**Issue by odradek71** [faye/faye#534]
I had a server crash due to ECONNRESET which I cannot reproduce and I have theorized was caused by client protocol error.  I was concerned if when faye creates websocket instance it needs to add an error listener, as described here https://github.com/websockets/ws/issues/1256
Thanks! I love faye!

**Comment by jcoglan** [comment]
We do add an `error` event handler in the [_configureStream()](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket/api.js#L130) method. This is called from [the API constructor](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket/api.js#L54), which itself is called from the server-side [WebSocket constructor](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket.js#L26) and from the [Client constructor](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket/client.js#L49). These should all catch an error emitted by the TCP/TLS stream during operation.

If you're still seeing connection-level errors come up in your application, I'd suggest monitoring those event listeners to see if they're emitting things we're not checking for.

**Comment by jcoglan** [comment]
It's also worth checking the driver's `error` events which are caught [here on the server side](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket/api.js#L39-L42) and [here on the client side](https://github.com/faye/faye-websocket-node/blob/0.11.4/lib/faye/websocket/client.js#L20-L25).

On the server, we add a do-nothing `error` listener so that `error` events don't crash the application. On the client side we let these events bubble out of the `WebSocket` instance, but Faye itself listens to them in [the websocket transport code](https://github.com/faye/faye/blob/1.4.0/src/transport/web_socket.js#L70) so they should be caught and trigger a reconnection.

**Comment by odradek71** [comment]
Thanks very much for the quick response and for highlighting these sections of the code.  I will monitor these events as you suggest and if I find anything of note I'll post again!

**Comment by odradek71** [comment]
Just to update, my website has been up continuously for the 3+ years since I filed this issue, and whatever bizarre circumstance caused the original crash, it has not happened again!
