### ISSUE TITLE
grammer.rb ERROR using greedy regex operators ReDoS Vulnerability

### ISSUE THREAD

**Issue by vhochstein** [faye/faye#538]
According to
https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

greedy regex operators should nt be used.

if you take a look at grammer.js for latest version ERROR regex will look as follows and includes greedy operators:
`ERROR:            /^([0-9][0-9][0-9]:(((([a-z]|[A-Z])|[0-9])|(\-|\_|\!|\~|\(|\)|\$|\@)| |\/|\*|\.))*(,(((([a-z]|[A-Z])|[0-9])|(\-|\_|\!|\~|\(|\)|\$|\@)| |\/|\*|\.))*)*:(((([a-z]|[A-Z])|[0-9])|(\-|\_|\!|\~|\(|\)|\$|\@)| |\/|\*|\.))*|[0-9][0-9][0-9]::(((([a-z]|[A-Z])|[0-9])|(\-|\_|\!|\~|\(|\)|\$|\@)| |\/|\*|\.))*)$/,`

Would be great if that vulnerability could be fixed.
Thanks a lot for your support in advance.

**Comment by jcoglan** [comment]
Do you have an example of an input that a client could send to the server that would cause super-linear parsing time?

**Comment by jcoglan** [comment]
Also I should have said, if you believe you have found a vulnerability in a piece of software, please contact the maintainers privately via a secure channel first rather than posting it on their public issue tracker.

**Comment by jcoglan** [comment]
To be on the safe side, I took the time to analyse the above pattern to see if it is indeed vulnerable to ReDoS. Here is a copy of the regex that I've formatted so that its structure is easier to see:

    /^(
      [0-9][0-9][0-9]:(
        (
          (
            ([a-z]|[A-Z])
          |
            [0-9]
          )
        |
          (\-|\_|\!|\~|\(|\)|\$|\@)
          | |\/|\*|\.
        )
      )*(
        ,(
          (
            (
              ([a-z]|[A-Z])
            |
              [0-9]
            )
          |
            (\-|\_|\!|\~|\(|\)|\$|\@)
            | |\/|\*|\.
          )
        )*
      )*:(
        (
          (
            ([a-z]|[A-Z])
          |
            [0-9]
          )
        |
          (\-|\_|\!|\~|\(|\)|\$|\@)
          | |\/|\*|\.
        )
      )*
    |
      [0-9][0-9][0-9]::(
        (
          (
            ([a-z]|[A-Z])
          |
            [0-9]
          )
        |
          (\-|\_|\!|\~|\(|\)|\$|\@)
          | |\/|\*|\.
        )
      )*
    )$/

As you've probably guessed, these patterns are generated from the code in `lib/faye/protocol/grammar.rb` and are not hand-written. There are two main candidates for ReDoS in this pattern: a repeated alternation, and a nested repetition. The first comes from the structure that is repeated several times above, the pattern for `STRING` in the grammar:

    (
      (
        (
          ([a-z]|[A-Z])
        |
          [0-9]
        )
      |
        (\-|\_|\!|\~|\(|\)|\$|\@)
        | |\/|\*|\.
      )
    )*

There is some superfluous nesting/grouping here just because of how the pattern is generated, but what it essentially matches is zero or more of one of the following choices:

- the letters `a` to `z`
- the letters `A` to `Z`
- the digits `0` to `9`
- the characters `-`, `_`, `!`, `~`, `(`, `)`, `$` or `@`
- a space, or `/`, `*` or `.`

There are no characters in common between any of these choices so there is only one way it could match a given input, and none of the ambiguous choices that would make it vulnerable to ReDoS. Also note that each of the possible choices will always match exactly one character of input, so it's not possible for it to introduce ambiguity by matching varying amounts of the input when backtracking.

The other risky structure here is a nested repetition:

    (
      ,(
        (
          (
            ([a-z]|[A-Z])
          |
            [0-9]
          )
        |
          (\-|\_|\!|\~|\(|\)|\$|\@)
          | |\/|\*|\.
        )
      )*
    )*

This matches zero or more instances of a comma (`,`) followed by the `STRING` pattern from above. The `STRING` pattern does not match `,` in any of its branches, so it cannot create ambiguous parses; an input like `,,,,,,,,` can only be parsed as a sequence of "one comma followed by an empty string", rather than grouping the commas in any other way. This is equivalent to the pattern `(ab*)*` which is safe.

Fundamentally the pattern is safe because the grammar it represents is unambiguous; the separators like `:` and `,` that it uses are not allowed to appear in variable-length data sections, and the data sections do not contain ambiguous choices.

As an example of this pattern being safe, here is a script that matches both a complete and an incomplete error message containing a large number of empty strings:

```js
let { ERROR } = require('./src/protocol/grammar')

let commas = new Array(500).fill('').join(',')

let result = ERROR.test('400:' + commas + ':')
console.log(result)

result = ERROR.test('400:' + commas)
console.log(result)
```

This program runs quickly and does not take exponential time to reject the incomplete input. If we changed the definition of `STRING` so that it allowed `,` to be included, then the pattern would indeed be vulnerable.

**Comment by jcoglan** [comment]
I have also run all the regexes in the `grammar.js` file through an [automated ReDoS checker](https://devina.io/redos-checker) that reported they all run in linear time.

**Comment by jcoglan** [comment]
I'm going to close this, as for the reasons given above I don't believe there is any problem with the regexes as written. If you do find a vulnerability with a usable exploit, please communicate this to me privately, and not on Github.
